version: '2'
services:
    cms-app:
        image: cms
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cms-postgresql:5432/admission
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cms-elasticsearch:9300
        ports:
            - 8080:8080
        links:
            - cms-postgresql:cms-postgresql
            - cms-elasticsearch:cms-elasticsearch
    cms-postgresql:
        extends:
            file: postgresql.yml
            service: cms-postgresql
    cms-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cms-elasticsearch
